### ISSUE TITLE
Random does not apply.

### ISSUE THREAD

**Issue by scd02** [XLuma/SV-Randomizer#10]
I watched XLuma's YouTube video and made a random one after installing Python 3.10, but it didn't apply.

<Details>
0. Randemizer version: 1.3.0
1. Python Version: v3.10
2. Software: Pokemon Scarlet (v1.2.0)
3. Random application: Starter, trainer, TM, etc

**Comment by XLuma** [comment]
redump your game's romfs to match 1.2.0
make sure you correctly create the patch with trinity loader too. the randomizer has nothing to do with any problems of "not working"

**Comment by scd02** [comment]
You can apply it again.
'romfs' was found to be applied incorrectly in 'trinity loader'.
Thank you.
