### ISSUE TITLE
Not an Issue.

### ISSUE THREAD

**Issue by Extendoz** [XLuma/SV-Randomizer#11]
I am not having any issues but just a question and I'm not sure how to use GitHub to contact you lol so sorry in advance. Is there a way to merge the spawn locations(land,water,air) from the clean pokedata array to the randomizer modified array one? I just want land pokemon to only spawn on land and water pokemon to only be in the water, etc. The problem is that land pokemon are spawning in the water and falling straight down to the bottom of the water and I can't see them anymore. Shallow waters are not a problem though. Let me know and if it's easy to do myself without having to copy and paste over and over. Thank you! Love and appreciate this work of yours!

**Comment by XLuma** [comment]
If you are able to code, you could make a very simple program to read both files, and for every entry to copy the data you want from the clean file to the randomized file and save it back.
