### ISSUE TITLE
Black screen after cutscene at beginning of game

### ISSUE THREAD

**Issue by seobck** [XLuma/SV-Randomizer#16]
I'm getting a black screen after the cutscene right at the beginning of the game, after it zooms in to the house. My version is 1.2.0, pokemon scarlet, using ryujinx 1.1.965.

[config.txt](https://github.com/XLuma/SV-Randomizer/files/12098890/config.txt)

**Comment by XLuma** [comment]
Did you patch with Trinity ?

**Comment by seobck** [comment]
> 

yeah, I used trinity loader to apply it.

**Comment by XLuma** [comment]
Dunno. I'd suggest trying with patch_trpfd and not using trinity maybe just to check,  i cant tell if its a rando issue or a trinity issue

**Comment by seobck** [comment]
Sorry, I had a dumped version of pokemon 1.0.1, I dumped the 1.2.0 and did it and it worked. thanks
