### ISSUE TITLE
Pokemon having no Attacks

### ISSUE THREAD

**Issue by Normuu** [XLuma/SV-Randomizer#19]
Everything works fine, but if i activate the personal data randomizer, every starter and random encounter has no type and attacks and can only use struggle. When i deactivate it everything works fine. Anyone knows how to fix this?

![53d2a845c0ba3686af0384776a0e60d3](https://github.com/XLuma/SV-Randomizer/assets/145396380/c009fd13-cd56-4400-9302-98eef2e227fa)
![7b4ca4118dfe948f4bf57823efdd9156](https://github.com/XLuma/SV-Randomizer/assets/145396380/75759b45-112c-4d7f-b164-50720d018d0a)
![1760e97408479add31d9fd184d182e53](https://github.com/XLuma/SV-Randomizer/assets/145396380/a89c1b92-161e-42d5-9cf7-50bb239d2a5c)
![140a0a0078cb61ea641fa7cbb988675f](https://github.com/XLuma/SV-Randomizer/assets/145396380/e66f18dc-9d31-4d08-91b8-2e7c812a2370)

**Comment by XLuma** [comment]
the randomizer doesnt work with 2.0.1

**Comment by Normuu** [comment]
ok that would explain the problems, thank you
