### ISSUE TITLE
Randomized Starters do not have a type or moves

### ISSUE THREAD

**Issue by herrobro** [XLuma/SV-Randomizer#21]
Exactly as the title says, randomized starters appear in the overworld, but when I choose one it has a type as "typeicon" and no moves. Abilities randomize just fine, but as soon as I go to battle the game crashes, as there are no moves to select. 
I am on version 3.0.0 if that is an issue with this randomizer.
![unknown_2023 12 17-11 45](https://github.com/XLuma/SV-Randomizer/assets/154090488/c3f0bd79-3d24-480e-8097-6a31a359bb9c)
![unknown_2023 12 17-11 45_1](https://github.com/XLuma/SV-Randomizer/assets/154090488/ce3cdd25-3927-4529-8de6-f3a3ca0f8ceb)

**Comment by Jack22017** [comment]
This not only goes for the starters but goes for every wild pokemon aswell, i am having the same issue

**Comment by herrobro** [comment]
> This not only goes for the starters but goes for every wild pokemon aswell, i am having the same issue

I would assume this is an issue with the version of the game, as I checked the closed issues and saw that the randomizer does not work with version 2.0.1, so it is a safe assumption that it does not work with version 3.0.0.

**Comment by herrobro** [comment]
Confirmed. Tried it on update 1.3.1 and it worked. Sorry for opening without reason :)
