### ISSUE TITLE
It's not loading the spawns of wild Pokémon after a while, and the starter and other Pokémon are appearing without moves.

### ISSUE THREAD

**Issue by Costly81** [XLuma/SV-Randomizer#23]
-This works with version 3.0.0 and the new DLC

-It's not loading the spawns of wild Pokémon after a while, and the starter and other Pokémon are appearing without abilities.

-This is my configuration:
{
    "wild_randomizer": {
        "is_enabled": "yes",
        "exclude_legendaries": "no"
    },
    "trainer_randomizer": {
        "is_enabled": "yes",
        "force_6_pokemons_on_important_trainers": "yes",
        "force_perfect_ivs": "no",
        "make_ai_smart_for_all_trainers": "no",
        "allow_all_trainers_to_terastalize": "no",
        "randomize_fixed_tera_type": "no",
        "randomize_all_tera_type": "no"
    },
    "personal_data_randomizer": {
        "is_enabled": "no",
        "randomize_abilities": "yes",
        "ban_wonder_guard": "yes",
        "randomize_movesets": "yes",
        "randomize_evolutions": "yes"
    },
    "starter_randomizer": {
        "is_enabled": "yes",
        "randomize_all_gifts": "yes",
        "randomize_tera_type": "yes",
        "show_starters_in_overworld": "yes"
    },
    "static_randomizer": {
        "is_enabled": "yes",
        "randomize_tera_type_for_static_tera": "yes"
    },
    "tm_randomizer": {
        "is_enabled": "yes"
    },
    "patch_trpfd": "no"
}

**Comment by XLuma** [comment]
read the README. it only supports 1.2 and 1.3
