### ISSUE TITLE
Syntax Issue even with Python 3.10 installed

### ISSUE THREAD

**Issue by Thewindyfan** [XLuma/SV-Randomizer#7]
Hi, 

Having the same issue as one of the issues already closed with regards to launching the bat file and seeing a "Syntax error, please press any key to continue", however I already have Python 3.10 installed properly via browser instead of the windows app. Would appreciate any advise on what is being done incorrectly here, thank you!
![image_2023-01-15_222454516](https://user-images.githubusercontent.com/122767142/212598411-408a096e-9982-496a-9f39-43c0d9563dba.png)

**Comment by XLuma** [comment]
No idea what is happening there. Maybe try with python from the windows store if possible ? the error doesnt really make any sense...

**Comment by Thewindyfan** [comment]
Yeah, the issue persists even after doing a full uninstall and reinstall of Python 3.10 :c 

Hopefully someone else can advise on resolving this soon

**Comment by XLuma** [comment]
do you have python 2.7 by any chance ?

**Comment by Thewindyfan** [comment]
Yep that was it, I had Python 2.7.8 installed at the same time as Python 3.1.0 - someone in Pointcrow's discord helped direct my attention to that and now the batch file works as intended. Thanks!
